-- Products Table
CREATE TABLE IF NOT EXISTS "Products" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT,
  customizable BOOLEAN DEFAULT false,
  rating NUMERIC DEFAULT 5,
  tag TEXT
);

-- ProductVariants Table
CREATE TABLE IF NOT EXISTS "ProductVariants" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  product_id BIGINT REFERENCES "Products"(id) ON DELETE CASCADE,
  view TEXT NOT NULL, -- FRONT, BACK, LEFT, RIGHT
  color TEXT NOT NULL,
  image_url TEXT
);

-- DesignAreas Table
CREATE TABLE IF NOT EXISTS "DesignAreas" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  product_id BIGINT REFERENCES "Products"(id) ON DELETE CASCADE,
  view TEXT NOT NULL,
  x NUMERIC NOT NULL,
  y NUMERIC NOT NULL,
  width NUMERIC NOT NULL,
  height NUMERIC NOT NULL
);

-- ProductImages Table (for user uploads history)
CREATE TABLE IF NOT EXISTS "ProductImages" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  product_id BIGINT REFERENCES "Products"(id) ON DELETE CASCADE,
  view TEXT NOT NULL,
  url TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE "Products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductVariants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DesignAreas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductImages" ENABLE ROW LEVEL SECURITY;

-- Policies
-- Public Read Access
CREATE POLICY "Public Read Products" ON "Products" FOR SELECT USING (true);
CREATE POLICY "Public Read ProductVariants" ON "ProductVariants" FOR SELECT USING (true);
CREATE POLICY "Public Read DesignAreas" ON "DesignAreas" FOR SELECT USING (true);
CREATE POLICY "Public Read ProductImages" ON "ProductImages" FOR SELECT USING (true);

-- Authenticated Write Access (For Admin - assuming any auth user is admin for now for simplicity, or just open for dev)
-- Ideally you'd have a role check like: (auth.jwt() ->> 'role' = 'admin')
CREATE POLICY "Auth Write Products" ON "Products" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Write ProductVariants" ON "ProductVariants" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Write DesignAreas" ON "DesignAreas" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Write ProductImages" ON "ProductImages" FOR ALL USING (auth.role() = 'authenticated');
