-- Create Order table if it doesn't exist
CREATE TABLE IF NOT EXISTS "Order" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  product_id BIGINT,
  customizations JSONB,
  file_url TEXT,
  status TEXT DEFAULT 'pending_confirmation',
  contact_info JSONB,
  total_price NUMERIC DEFAULT 0
);

-- Enable Row Level Security
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can insert their own orders
CREATE POLICY "Users can insert their own orders" 
ON "Order" 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can view their own orders
CREATE POLICY "Users can view their own orders" 
ON "Order" 
FOR SELECT 
USING (auth.uid() = user_id);

-- Policy: Users can update their own orders (for cancellation and completing checkout)
CREATE POLICY "Users can update their own orders" 
ON "Order" 
FOR UPDATE 
USING (auth.uid() = user_id);

-- Create storage bucket for orders if it doesn't exist (you might need to do this via UI or API if SQL fails)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('orders', 'orders', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policy: Users can upload to their own folder (optional refinement, but generally auth users can upload)
CREATE POLICY "Authenticated users can upload files"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'orders');

-- Storage Policy: Users can read files
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'orders');
