-- Create Order table
CREATE TABLE IF NOT EXISTS "Order" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  product_id BIGINT,
  customizations JSONB,
  file_url TEXT,
  status TEXT DEFAULT 'pending_confirmation',
  contact_info JSONB,
  total_price NUMERIC DEFAULT 0
);

-- Enable RLS on Order table
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;

-- Policy for users to insert their own orders
CREATE POLICY "Users can insert their own orders"
ON "Order"
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Policy for users to view their own orders
CREATE POLICY "Users can view their own orders"
ON "Order"
FOR SELECT
USING (auth.uid() = user_id);

-- Policy for users to update their own orders (e.g., adding contact info)
CREATE POLICY "Users can update their own orders"
ON "Order"
FOR UPDATE
USING (auth.uid() = user_id);

-- Create Storage Bucket for orders if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('orders', 'orders', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policy: Users can upload order files
CREATE POLICY "Users can upload order files"
ON storage.objects
FOR INSERT
WITH CHECK (
  bucket_id = 'orders' AND
  auth.role() = 'authenticated'
);

-- Storage Policy: Users can read order files
CREATE POLICY "Public can read order files"
ON storage.objects
FOR SELECT
USING (bucket_id = 'orders');
